export type RedisCommandSafety = "allowed" | "write" | "confirm" | "blocked";

const BLOCKED_COMMANDS = new Set(["KEYS", "FLUSHALL", "SHUTDOWN", "CONFIG", "SAVE", "BGSAVE", "SLAVEOF", "REPLICAOF", "MIGRATE", "MODULE", "SCRIPT", "EVAL", "EVALSHA"]);

// Explicit allowlist matching the backend's read-command classification.
// Unknown commands fall through to "blocked" (fail-closed).
const ALLOWED_COMMANDS = new Set([
  "GET",
  "MGET",
  "GETRANGE",
  "GETBIT",
  "GETSET",
  "GETDEL",
  "GETEX",
  "HEXISTS",
  "HGET",
  "HGETALL",
  "HKEYS",
  "HLEN",
  "HMGET",
  "HRANDFIELD",
  "HSCAN",
  "HSTRLEN",
  "HPTTL",
  "HTTL",
  "HVALS",
  "LINDEX",
  "LLEN",
  "LPOS",
  "LRANGE",
  "SCARD",
  "SDIFF",
  "SINTER",
  "SINTERCARD",
  "SISMEMBER",
  "SMEMBERS",
  "SMISMEMBER",
  "SRANDMEMBER",
  "SSCAN",
  "STRLEN",
  "SUBSTR",
  "TYPE",
  "EXISTS",
  "TTL",
  "PTTL",
  "OBJECT",
  "ZCARD",
  "ZCOUNT",
  "ZDIFF",
  "ZINTER",
  "ZINTERCARD",
  "ZLEXCOUNT",
  "ZMSCORE",
  "ZRANDMEMBER",
  "ZRANGE",
  "ZRANGEBYLEX",
  "ZRANGEBYSCORE",
  "ZRANK",
  "ZREVRANGE",
  "ZREVRANGEBYLEX",
  "ZREVRANGEBYSCORE",
  "ZREVRANK",
  "ZSCAN",
  "ZSCORE",
  "ZUNION",
  "XINFO",
  "XLEN",
  "XPENDING",
  "XRANGE",
  "XREVRANGE",
  "XREAD",
  "PFCOUNT",
  "GEOHASH",
  "GEOPOS",
  "GEODIST",
  "GEOSEARCH",
  "GEORADIUS_RO",
  "GEORADIUSBYMEMBER_RO",
  "DBSIZE",
  "LASTSAVE",
  "TIME",
  "PING",
  "ECHO",
  "WAIT",
  "WAITAOF",
  "ROLE",
  "COMMAND",
  "INFO",
  "SLOWLOG",
  "SCAN",
  "RANDOMKEY",
  "JSON.GET",
  "JSON.MGET",
  "JSON.OBJKEYS",
  "JSON.OBJLEN",
  "JSON.STRLEN",
  "JSON.TYPE",
  "JSON.ARRINDEX",
  "JSON.ARRLEN",
  "JSON.RESP",
  "FT.INFO",
  "FT.SEARCH",
  "FT.AGGREGATE",
  "FT.SPELLCHECK",
  "FT.SYNDUMP",
  "FT.TAGVALS",
  "FT.DICTDUMP",
  "FT.EXPLAIN",
  "FT.EXPLAINCLI",
  "FT.PROFILE",
  "BF.EXISTS",
  "BF.INFO",
  "BF.CARD",
  "BF.MEXISTS",
  "CF.EXISTS",
  "CF.INFO",
  "CF.COUNT",
  "CF.MEXISTS",
  "CMS.INFO",
  "CMS.QUERY",
  "TS.GET",
  "TS.INFO",
  "TS.MGET",
  "TS.MRANGE",
  "TS.QUERYINDEX",
  "TS.RANGE",
  "TDIGEST.BYRANK",
  "TDIGEST.BYREVRANK",
  "TDIGEST.CDF",
  "TDIGEST.INFO",
  "TDIGEST.MAX",
  "TDIGEST.MIN",
  "TDIGEST.QUANTILE",
  "TDIGEST.RANK",
  "TDIGEST.REVRANK",
  "TDIGEST.TRIMMED_MEAN",
  "TOPK.INFO",
  "TOPK.LIST",
  "TOPK.QUERY",
]);

const CONFIRM_COMMANDS = new Set([
  "DEL",
  "UNLINK",
  "EXPIRE",
  "EXPIREAT",
  "PEXPIRE",
  "PEXPIREAT",
  "RENAME",
  "RENAMENX",
  "GETDEL",
  "HDEL",
  "HEXPIRE",
  "HEXPIREAT",
  "HPEXPIRE",
  "HPEXPIREAT",
  "HPERSIST",
  "JSON.ARRPOP",
  "JSON.ARRTRIM",
  "JSON.CLEAR",
  "JSON.DEL",
  "JSON.FORGET",
  "BLMOVE",
  "BLMPOP",
  "BLPOP",
  "BRPOP",
  "BRPOPLPUSH",
  "LPOP",
  "LMOVE",
  "LMPOP",
  "RPOP",
  "RPOPLPUSH",
  "LREM",
  "LTRIM",
  "SPOP",
  "SREM",
  "ZREM",
  "ZPOPMAX",
  "ZPOPMIN",
  "ZMPOP",
  "BZMPOP",
  "BZPOPMAX",
  "BZPOPMIN",
  "ZREMRANGEBYLEX",
  "ZREMRANGEBYRANK",
  "ZREMRANGEBYSCORE",
  "XDEL",
  "XTRIM",
  "MOVE",
  "SORT",
  "SDIFFSTORE",
  "SINTERSTORE",
  "SUNIONSTORE",
  "ZDIFFSTORE",
  "ZINTERSTORE",
  "ZRANGESTORE",
  "ZUNIONSTORE",
  "PFMERGE",
  "GEOSEARCHSTORE",
  "FLUSHDB",
]);

const WRITE_COMMANDS = new Set([
  "APPEND",
  "BITFIELD",
  "BITOP",
  "COPY",
  "DECR",
  "DECRBY",
  "GEOADD",
  "GEORADIUS",
  "GEORADIUSBYMEMBER",
  "GETSET",
  "INCR",
  "INCRBY",
  "INCRBYFLOAT",
  "SET",
  "SETEX",
  "PSETEX",
  "SETNX",
  "SETRANGE",
  "MSET",
  "MSETNX",
  "PERSIST",
  "HSET",
  "HMSET",
  "HINCRBY",
  "HINCRBYFLOAT",
  "HSETNX",
  "LINSERT",
  "LSET",
  "LMOVE",
  "LPUSH",
  "LPUSHX",
  "PFADD",
  "RPUSH",
  "RPUSHX",
  "RESTORE",
  "SADD",
  "ZADD",
  "ZINCRBY",
  "SETBIT",
  "XADD",
  "XACK",
  "XAUTOCLAIM",
  "XCLAIM",
  "XSETID",
]);

export function firstRedisCommandToken(command: string): string {
  const trimmed = command.trimStart();
  if (!trimmed) return "";

  const quote = trimmed[0] === '"' || trimmed[0] === "'" ? trimmed[0] : "";
  let token = "";
  let escaping = false;
  for (let i = quote ? 1 : 0; i < trimmed.length; i++) {
    const ch = trimmed[i];
    if (escaping) {
      token += ch;
      escaping = false;
      continue;
    }
    if (ch === "\\") {
      escaping = true;
      continue;
    }
    if (quote && ch === quote) break;
    if (!quote && /\s/.test(ch)) break;
    token += ch;
  }
  return token.toUpperCase();
}

export function classifyRedisCommandSafety(command: string): RedisCommandSafety {
  const token = firstRedisCommandToken(command);
  if (BLOCKED_COMMANDS.has(token)) return "blocked";
  if (CONFIRM_COMMANDS.has(token)) return "confirm";
  if (WRITE_COMMANDS.has(token)) return "write";
  if (ALLOWED_COMMANDS.has(token)) return "allowed";
  // Unknown commands are treated as blocked (fail-closed) to match the
  // backend classification which rejects unrecognized commands.
  return "blocked";
}
