// Mirrors crates/dbx-core/src/docs/snapshot.rs. There is no Rust->TS codegen
// in this repo, so this file is maintained by hand — see
// __tests__/fixtureConformance.spec.ts, which validates it against a snapshot
// generated by the real Rust code and fails if the two drift apart.

export type TableKind = "TABLE" | "VIEW" | "MATERIALIZED_VIEW";
export type NoteSource = "DATABASE" | "LOCAL" | "NONE";
export type Cardinality = "ONE_TO_ONE" | "MANY_TO_ONE";

export interface ColumnInfo {
  name: string;
  data_type: string;
  is_nullable: boolean;
  column_default: string | null;
  is_primary_key: boolean;
  extra: string | null;
  // No skip_serializing_if in Rust — these keys are ALWAYS present, so they
  // are required and may be null. Marking them optional would let `undefined`
  // reach code that checks `=== null`.
  comment: string | null;
  numeric_precision: number | null;
  numeric_scale: number | null;
  character_maximum_length: number | null;
  // These three DO carry skip_serializing_if, so the key is absent rather
  // than null when there is no value.
  enum_values?: string[];
  character_set?: string;
  collation?: string;
}

export interface IndexInfo {
  name: string;
  columns: string[];
  is_unique: boolean;
  is_primary: boolean;
  // No skip_serializing_if on any of these in Rust — required, may be null.
  filter: string | null;
  index_type: string | null;
  included_columns: string[] | null;
  comment: string | null;
}

export interface ForeignKeyInfo {
  name: string;
  column: string;
  ref_schema?: string | null;
  ref_table: string;
  ref_column: string;
  on_update?: string | null;
  on_delete?: string | null;
}

export interface ProjectMeta {
  name: string;
  databaseType: string;
  database: string | null;
  schemas: string[];
  generatedAt: string;
  note: string | null;
}

export interface ColumnNote {
  note: string;
  source: NoteSource;
  shadowed: string | null;
}

export interface DocTable {
  schema: string | null;
  name: string;
  kind: TableKind;
  columns: ColumnInfo[];
  indexes: IndexInfo[];
  foreignKeys: ForeignKeyInfo[];
  groupId: string | null;
  note: string | null;
  noteSource: NoteSource;
  shadowedNote: string | null;
  columnNotes: Record<string, ColumnNote>;
  estimatedRows: number | null;
  viewDefinition: string | null;
}

export interface TableGroup {
  id: string;
  name: string;
  /** 0-359. Lightness and chroma are theme-controlled in CSS. */
  hue: number;
  note: string | null;
}

export interface FieldRef {
  schema: string | null;
  table: string;
  column: string;
}

export interface Relationship {
  id: string;
  name: string | null;
  from: FieldRef;
  to: FieldRef;
  cardinality: Cardinality;
  onUpdate: string | null;
  onDelete: string | null;
}

export interface DocEnum {
  schema: string | null;
  name: string;
  values: string[];
  note: string | null;
  synthesized: boolean;
}

/**
 * Internally tagged on a camelCase `kind`. Note this differs from
 * TableKind/NoteSource/Cardinality, which are SCREAMING_SNAKE — the Rust enum
 * carries both `tag = "kind"` and `rename_all = "camelCase"`.
 */
export type SnapshotWarning =
  | { kind: "tableSkipped"; table: string; reason: string }
  | { kind: "noForeignKeyMetadata"; engine: string }
  | { kind: "commentsUnsupported"; engine: string }
  | { kind: "orphanedNotes"; count: number }
  | { kind: "dbmlOmitted"; table: string; item: string; reason: string };

export interface SchemaSnapshot {
  formatVersion: number;
  project: ProjectMeta;
  tables: DocTable[];
  relationships: Relationship[];
  groups: TableGroup[];
  enums: DocEnum[];
  warnings: SnapshotWarning[];
}

/** Mirrors `dbx_core::docs::annotations::ColumnAnnotation`. */
export interface ColumnAnnotation {
  note: string;
}

/** Mirrors `TableAnnotation`. Absent keys are omitted, never sent as null. */
export interface TableAnnotation {
  group?: string;
  note?: string;
  columns?: Record<string, ColumnAnnotation>;
}

/** Mirrors `GroupAnnotation`. `hue` is 0–359; lightness and chroma are the theme's. */
export interface GroupAnnotation {
  id: string;
  name: string;
  hue: number;
  note?: string;
}

/** Mirrors `ProjectAnnotation`. */
export interface ProjectAnnotation {
  name?: string;
  note?: string;
}

/**
 * The on-disk notes file. Rust declares `deny_unknown_fields`, so adding a
 * property here without adding it in Rust makes every save fail.
 */
export interface AnnotationFile {
  formatVersion: number;
  project?: ProjectAnnotation;
  groups?: GroupAnnotation[];
  tables?: Record<string, TableAnnotation>;
}

/**
 * What the viewer asks its host to do. The viewer never persists anything —
 * that is what keeps `src/docs/` free of backend calls and bundleable into a
 * standalone HTML file.
 */
export type DocsEdit =
  | { kind: "projectNote"; note: string }
  | { kind: "tableNote"; tableKey: string; note: string }
  | { kind: "columnNote"; tableKey: string; column: string; note: string }
  | { kind: "tableGroup"; tableKey: string; groupId: string | null }
  | { kind: "upsertGroup"; group: GroupAnnotation }
  | { kind: "removeGroup"; groupId: string };

/**
 * Runtime witnesses for the interfaces above.
 *
 * TypeScript types are erased at runtime, so a test cannot enumerate an
 * interface's keys. `Record<keyof T, true>` gives a value that IS enumerable
 * and that `vue-tsc` checks against the interface: add a field and this object
 * is missing a key; remove one and it carries an excess property. Either way
 * the build fails here rather than at a user's save.
 *
 * These live in this file, not in the spec, because `tsconfig.json` excludes
 * `src/**\/__tests__/**` from `vue-tsc` — witnesses in a spec file would be
 * checked by nothing.
 */
export const COLUMN_ANNOTATION_KEYS: Record<keyof ColumnAnnotation, true> = { note: true };
export const TABLE_ANNOTATION_KEYS: Record<keyof TableAnnotation, true> = { group: true, note: true, columns: true };
export const GROUP_ANNOTATION_KEYS: Record<keyof GroupAnnotation, true> = { id: true, name: true, hue: true, note: true };
export const PROJECT_ANNOTATION_KEYS: Record<keyof ProjectAnnotation, true> = { name: true, note: true };
export const ANNOTATION_FILE_KEYS: Record<keyof AnnotationFile, true> = {
  formatVersion: true,
  project: true,
  groups: true,
  tables: true,
};
