import type { ClickHouseFunctionCategory, ClickHouseFunctionDefinition, ClickHouseFunctionSignature } from "./functionTypes";

/**
 * Static name snapshot from ClickHouse Playground system.functions on 2026-07-31.
 * Runtime completion never queries a ClickHouse server.
 */
const CLICKHOUSE_REGULAR_NAMES_BY_CATEGORY: Partial<Record<ClickHouseFunctionCategory, string>> = {
  array:
    "array arrayAll arrayAUCPR arrayAutocorrelation arrayAvg arrayBottomK arrayCompact arrayConcat arrayCount arrayCumSum arrayCumSumNonNegative arrayDifference arrayDistinct arrayDotProduct arrayElement arrayElementOrNull arrayEnumerate arrayEnumerateDense arrayEnumerateDenseRanked arrayEnumerateUniq arrayEnumerateUniqRanked arrayExcept arrayExists arrayFill arrayFilter arrayFirst arrayFirstIndex arrayFirstOrNull arrayFlatten arrayFold arrayIntersect arrayJaccardIndex arrayJoin arrayLast arrayLastIndex arrayLastOrNull arrayLevenshteinDistance arrayLevenshteinDistanceWeighted arrayMap arrayMax arrayMin arrayNormalizedGini arrayPartialReverseSort arrayPartialShuffle arrayPartialSort arrayPopBack arrayPopFront arrayProduct arrayPushBack arrayPushFront arrayRandomSample arrayReduce arrayReduceInRanges arrayRemove arrayResize arrayReverse arrayReverseFill arrayReverseSort arrayReverseSplit arrayROCAUC arrayRotateLeft arrayRotateRight arrayShiftLeft arrayShiftRight arrayShingles arrayShuffle arraySimilarity arraySlice arraySort arraySplit arrayStringConcat arraySum arraySymmetricDifference arrayTopK arrayTranspose arrayUnion arrayUniq arrayWithConstant arrayZip arrayZipUnaligned",
  bitmap:
    "bitmapAnd bitmapAndCardinality bitmapAndnot bitmapAndnotCardinality bitmapBuild bitmapCardinality bitmapContains bitmapHasAll bitmapHasAny bitmapMax bitmapMin bitmapOr bitmapOrCardinality bitmapSubsetInRange bitmapSubsetLimit bitmapToArray bitmapTransform bitmapXor bitmapXorCardinality bitmaskToArray bitmaskToList subBitmap",
  comparison:
    "and empty emptyArrayDate emptyArrayDateTime emptyArrayFloat32 emptyArrayFloat64 emptyArrayInt16 emptyArrayInt32 emptyArrayInt64 emptyArrayInt8 emptyArrayString emptyArrayToSingle emptyArrayUInt16 emptyArrayUInt32 emptyArrayUInt64 emptyArrayUInt8 equals globalIn globalInIgnoreSet globalNotIn globalNotInIgnoreSet globalNotNullIn globalNotNullInIgnoreSet greater greaterOrEquals greatest has hasAll hasAllTokens hasAny hasAnyTokens if in isDistinctFrom isNotDistinctFrom least less lessOrEquals multiIf not notEmpty notEquals notIn notInIgnoreSet or xor",
  conversion:
    "accurateCast accurateCastOrDefault accurateCastOrNull CAST defaultValueOfArgumentType defaultValueOfTypeName dynamicElement dynamicType materialize reinterpret reinterpretAsDate reinterpretAsDateTime reinterpretAsFixedString reinterpretAsFloat32 reinterpretAsFloat64 reinterpretAsInt128 reinterpretAsInt16 reinterpretAsInt256 reinterpretAsInt32 reinterpretAsInt64 reinterpretAsInt8 reinterpretAsString reinterpretAsUInt128 reinterpretAsUInt16 reinterpretAsUInt256 reinterpretAsUInt32 reinterpretAsUInt64 reinterpretAsUInt8 reinterpretAsUUID toBFloat16 toBFloat16OrNull toBFloat16OrZero toBool toColumnTypeName toDecimal128 toDecimal128OrDefault toDecimal128OrNull toDecimal128OrZero toDecimal256 toDecimal256OrDefault toDecimal256OrNull toDecimal256OrZero toDecimal32 toDecimal32OrDefault toDecimal32OrNull toDecimal32OrZero toDecimal64 toDecimal64OrDefault toDecimal64OrNull toDecimal64OrZero toDecimalString toFixedString toFloat32 toFloat32OrDefault toFloat32OrNull toFloat32OrZero toFloat64 toFloat64OrDefault toFloat64OrNull toFloat64OrZero toInt128 toInt128OrDefault toInt128OrNull toInt128OrZero toInt16 toInt16OrDefault toInt16OrNull toInt16OrZero toInt256 toInt256OrDefault toInt256OrNull toInt256OrZero toInt32 toInt32OrDefault toInt32OrNull toInt32OrZero toInt64 toInt64OrDefault toInt64OrNull toInt64OrZero toInt8 toInt8OrDefault toInt8OrNull toInt8OrZero toInterval toIntervalDay toIntervalHour toIntervalMicrosecond toIntervalMillisecond toIntervalMinute toIntervalMonth toIntervalNanosecond toIntervalQuarter toIntervalSecond toIntervalWeek toIntervalYear toIPv4 toIPv4OrDefault toIPv4OrNull toIPv4OrZero toIPv6 toIPv6OrDefault toIPv6OrNull toIPv6OrZero toLowCardinality toNullable toString toStringCutToZero toTypeName toUInt128 toUInt128OrDefault toUInt128OrNull toUInt128OrZero toUInt16 toUInt16OrDefault toUInt16OrNull toUInt16OrZero toUInt256 toUInt256OrDefault toUInt256OrNull toUInt256OrZero toUInt32 toUInt32OrDefault toUInt32OrNull toUInt32OrZero toUInt64 toUInt64OrDefault toUInt64OrNull toUInt64OrZero toUInt8 toUInt8OrDefault toUInt8OrNull toUInt8OrZero toUUID toUUIDOrDefault toUUIDOrNull toUUIDOrZero variantElement variantType",
  "date-time":
    "addDate addDays addHours addInterval addMicroseconds addMilliseconds addMinutes addMonths addNanoseconds addQuarters addSeconds addWeeks addYears age changeDay changeHour changeMinute changeMonth changeSecond changeYear DATE dateDiff dateName dateTime64ToSnowflakeID dateTimeToSnowflakeID dateTimeToUUIDv7 dateTrunc formatDateTime formatDateTimeInJodaSyntax fromDaysSinceYearZero fromDaysSinceYearZero32 fromModifiedJulianDay fromModifiedJulianDayOrNull fromUnixTimestamp fromUnixTimestamp64Micro fromUnixTimestamp64Milli fromUnixTimestamp64Nano fromUnixTimestamp64Second fromUnixTimestampInJodaSyntax fromUTCTimestamp hop hopEnd hopStart makeDate makeDate32 makeDateTime makeDateTime64 monthName now now64 nowInBlock nowInBlock64 parseDateTime parseDateTime32BestEffort parseDateTime32BestEffortOrNull parseDateTime32BestEffortOrZero parseDateTime64 parseDateTime64BestEffort parseDateTime64BestEffortOrNull parseDateTime64BestEffortOrZero parseDateTime64BestEffortUS parseDateTime64BestEffortUSOrNull parseDateTime64BestEffortUSOrZero parseDateTime64InJodaSyntax parseDateTime64InJodaSyntaxOrNull parseDateTime64InJodaSyntaxOrZero parseDateTime64OrNull parseDateTime64OrZero parseDateTimeBestEffort parseDateTimeBestEffortOrNull parseDateTimeBestEffortOrZero parseDateTimeBestEffortUS parseDateTimeBestEffortUSOrNull parseDateTimeBestEffortUSOrZero parseDateTimeInJodaSyntax parseDateTimeInJodaSyntaxOrNull parseDateTimeInJodaSyntaxOrZero parseDateTimeOrNull parseDateTimeOrZero parseTimeDelta snowflakeIDToDateTime snowflakeIDToDateTime64 subtractDays subtractHours subtractInterval subtractMicroseconds subtractMilliseconds subtractMinutes subtractMonths subtractNanoseconds subtractQuarters subtractSeconds subtractWeeks subtractYears timeDiff timeSeriesCopyTag timeSeriesCopyTags timeSeriesExtractTag timeSeriesFromGrid timeSeriesGroupToSamplingKey timeSeriesGroupToTags timeSeriesIdToGroup timeSeriesIdToTags timeSeriesJoinTags timeSeriesRange timeSeriesRemoveAllTagsExcept timeSeriesRemoveTag timeSeriesRemoveTags timeSeriesReplaceTag timeSeriesStoreTags timeSeriesTagsToGroup timeSeriesThrowDuplicateSeriesIf timeSlot timeSlots timestamp timezone timezoneOf timezoneOffset toDate toDate32 toDate32OrDefault toDate32OrNull toDate32OrZero toDateOrDefault toDateOrNull toDateOrZero toDateTime toDateTime32 toDateTime64 toDateTime64OrDefault toDateTime64OrNull toDateTime64OrZero toDateTimeOrDefault toDateTimeOrNull toDateTimeOrZero today toDayOfMonth toDayOfWeek toDayOfYear toDaysInMonth toDaysSinceYearZero toHour toISOWeek toISOYear toLastDayOfMonth toLastDayOfWeek toMicrosecond toMillisecond toMinute toModifiedJulianDay toModifiedJulianDayOrNull toMonday toMonth toMonthNumSinceEpoch toNanosecond toQuarter toRelativeDayNum toRelativeHourNum toRelativeMinuteNum toRelativeMonthNum toRelativeQuarterNum toRelativeSecondNum toRelativeWeekNum toRelativeYearNum toSecond toStartOfDay toStartOfFifteenMinutes toStartOfFiveMinutes toStartOfHour toStartOfInterval toStartOfISOYear toStartOfMicrosecond toStartOfMillisecond toStartOfMinute toStartOfMonth toStartOfNanosecond toStartOfQuarter toStartOfSecond toStartOfTenMinutes toStartOfWeek toStartOfYear toTime toTime64 toTime64OrNull toTime64OrZero toTimeOrNull toTimeOrZero toTimeWithFixedDate toTimezone toUnixTimestamp toUnixTimestamp64Micro toUnixTimestamp64Milli toUnixTimestamp64Nano toUnixTimestamp64Second toUTCTimestamp toWeek toYear toYearNumSinceEpoch toYearWeek toYYYYMM toYYYYMMDD toYYYYMMDDhhmmss tumble tumbleEnd tumbleStart ULIDStringToDateTime UTCTimestamp yesterday YYYYMMDDhhmmssToDateTime YYYYMMDDhhmmssToDateTime64 YYYYMMDDToDate YYYYMMDDToDate32",
  dictionary:
    "dictGet dictGetAll dictGetChildren dictGetDate dictGetDateOrDefault dictGetDateTime dictGetDateTimeOrDefault dictGetDescendants dictGetFloat32 dictGetFloat32OrDefault dictGetFloat64 dictGetFloat64OrDefault dictGetHierarchy dictGetInt16 dictGetInt16OrDefault dictGetInt32 dictGetInt32OrDefault dictGetInt64 dictGetInt64OrDefault dictGetInt8 dictGetInt8OrDefault dictGetIPv4 dictGetIPv4OrDefault dictGetIPv6 dictGetIPv6OrDefault dictGetKeys dictGetOrDefault dictGetOrNull dictGetString dictGetStringOrDefault dictGetUInt16 dictGetUInt16OrDefault dictGetUInt32 dictGetUInt32OrDefault dictGetUInt64 dictGetUInt64OrDefault dictGetUInt8 dictGetUInt8OrDefault dictGetUUID dictGetUUIDOrDefault dictHas dictIsIn",
  encoding:
    "aes_decrypt_mysql aes_encrypt_mysql base32Decode base32Encode base58Decode base58Encode base64Decode base64Encode base64URLDecode base64URLEncode bech32Decode bech32Encode bin decodeHTMLComponent decodeURLComponent decodeURLFormComponent decodeXMLComponent decrypt encodeURLComponent encodeURLFormComponent encodeXMLComponent encrypt hex idnaDecode idnaEncode punycodeDecode punycodeEncode sqidDecode sqidEncode tryBase32Decode tryBase58Decode tryBase64Decode tryBase64URLDecode unbin unhex",
  geo: "areaCartesian areaSpherical flipCoordinates geoDistance geohashDecode geohashEncode geohashesInBox geoToH3 geoToS2 greatCircleAngle greatCircleDistance h3CellAreaM2 h3CellAreaRads2 h3Distance h3EdgeAngle h3EdgeLengthKm h3EdgeLengthM h3ExactEdgeLengthKm h3ExactEdgeLengthM h3ExactEdgeLengthRads h3GetBaseCell h3GetDestinationIndexFromUnidirectionalEdge h3GetFaces h3GetIndexesFromUnidirectionalEdge h3GetOriginIndexFromUnidirectionalEdge h3GetPentagonIndexes h3GetRes0Indexes h3GetResolution h3GetUnidirectionalEdge h3GetUnidirectionalEdgeBoundary h3GetUnidirectionalEdgesFromHexagon h3HexAreaKm2 h3HexAreaM2 h3HexRing h3IndexesAreNeighbors h3IsPentagon h3IsResClassIII h3IsValid h3kRing h3Line h3NumHexagons h3PointDistKm h3PointDistM h3PointDistRads h3PolygonToCells h3PolygonToCellsWithContainment h3ToCenterChild h3ToChildren h3ToGeo h3ToGeoBoundary h3ToParent h3ToString h3UnidirectionalEdgeIsValid MVTBoundingBox MVTBoundingBoxMercator MVTEncodeGeom perimeterCartesian perimeterSpherical pointInEllipses pointInPolygon polygonAreaCartesian polygonAreaSpherical polygonConvexHullCartesian polygonPerimeterCartesian polygonPerimeterSpherical polygonsDistanceCartesian polygonsDistanceSpherical polygonsEqualsCartesian polygonsIntersectCartesian polygonsIntersectionCartesian polygonsIntersectionSpherical polygonsIntersectSpherical polygonsSymDifferenceCartesian polygonsSymDifferenceSpherical polygonsUnionCartesian polygonsUnionSpherical polygonsWithinCartesian polygonsWithinSpherical readWKB readWKBLineString readWKBMultiLineString readWKBMultiPolygon readWKBPoint readWKBPolygon readWKT readWKTLineString readWKTMultiLineString readWKTMultiPolygon readWKTPoint readWKTPolygon readWKTRing s2CapContains s2CapUnion s2CellsIntersect s2GetNeighbors s2RectAdd s2RectContains s2RectIntersection s2RectUnion s2ToGeo",
  hash: "BLAKE3 cityHash64 CRC32 CRC32IEEE CRC64 farmFingerprint64 farmHash64 gccMurmurHash halfMD5 hiveHash icebergHash intHash32 intHash64 isDynamicElementInSharedData javaHash javaHashUTF16LE jumpConsistentHash kafkaMurmurHash keccak256 kostikConsistentHash MD4 MD5 metroHash64 murmurHash2_32 murmurHash2_64 murmurHash3_128 murmurHash3_32 murmurHash3_64 ngramMinHash ngramMinHashArg ngramMinHashArgCaseInsensitive ngramMinHashArgCaseInsensitiveUTF8 ngramMinHashArgUTF8 ngramMinHashCaseInsensitive ngramMinHashCaseInsensitiveUTF8 ngramMinHashUTF8 ngramSimHash ngramSimHashCaseInsensitive ngramSimHashCaseInsensitiveUTF8 ngramSimHashUTF8 normalizedQueryHash normalizedQueryHashKeepNames RIPEMD160 SHA1 SHA224 SHA256 SHA384 SHA512 SHA512_256 shardCount shardNum sipHash128 sipHash128Keyed sipHash128Reference sipHash128ReferenceKeyed sipHash64 sipHash64Keyed sparseGramsHashes sparseGramsHashesUTF8 URLHash wordShingleMinHash wordShingleMinHashArg wordShingleMinHashArgCaseInsensitive wordShingleMinHashArgCaseInsensitiveUTF8 wordShingleMinHashArgUTF8 wordShingleMinHashCaseInsensitive wordShingleMinHashCaseInsensitiveUTF8 wordShingleMinHashUTF8 wordShingleSimHash wordShingleSimHashCaseInsensitive wordShingleSimHashCaseInsensitiveUTF8 wordShingleSimHashUTF8 wyHash64 xxh3 xxh3_128 xxHash32 xxHash64",
  ip: "cutIPv6 IPv4CIDRToRange IPv4NumToString IPv4NumToStringClassC IPv4StringToNum IPv4StringToNumOrDefault IPv4StringToNumOrNull IPv4ToIPv6 IPv6CIDRToRange IPv6NumToString IPv6StringToNum IPv6StringToNumOrDefault IPv6StringToNumOrNull isIPAddressInRange isIPv4String isIPv6String MACNumToString MACStringToNum MACStringToOUI",
  json: "isValidJSON JSON_EXISTS JSON_QUERY JSON_VALUE JSONAllPaths JSONAllPathsWithTypes JSONAllValues JSONArrayLength JSONDynamicPaths JSONDynamicPathsWithTypes JSONExtract JSONExtractArrayRaw JSONExtractArrayRawCaseInsensitive JSONExtractBool JSONExtractBoolCaseInsensitive JSONExtractCaseInsensitive JSONExtractFloat JSONExtractFloatCaseInsensitive JSONExtractInt JSONExtractIntCaseInsensitive JSONExtractKeys JSONExtractKeysAndValues JSONExtractKeysAndValuesCaseInsensitive JSONExtractKeysAndValuesRaw JSONExtractKeysAndValuesRawCaseInsensitive JSONExtractKeysCaseInsensitive JSONExtractRaw JSONExtractRawCaseInsensitive JSONExtractString JSONExtractStringCaseInsensitive JSONExtractUInt JSONExtractUIntCaseInsensitive JSONHas JSONKey JSONLength JSONMergePatch JSONSharedDataPaths JSONSharedDataPathsWithTypes JSONType prettyPrintJSON simpleJSONExtractBool simpleJSONExtractFloat simpleJSONExtractInt simpleJSONExtractRaw simpleJSONExtractString simpleJSONExtractUInt simpleJSONHas toJSONString",
  map: "map mapAdd mapAll mapApply mapConcat mapContainsKey mapContainsKeyLike mapContainsValue mapContainsValueLike mapExists mapExtractKeyLike mapExtractValueLike mapFilter mapFromArrays mapKeys mapPartialReverseSort mapPartialSort mapPopulateSeries mapReverseSort mapSort mapSubtract mapUpdate mapValues",
  math: "abs acos acosh asin asinh atan atan2 atanh avg2 cbrt ceil clamp cos cosh cosineDistance cosineDistanceTransposed degrees divide divideDecimal divideOrNull dotProduct dotProductTransposed e erf erfc exp exp10 exp2 factorial floor gcd hypot intDiv intDivOrNull intDivOrZero intExp10 intExp2 L1Distance L1Norm L1Normalize L2Distance L2DistanceTransposed L2Norm L2Normalize L2SquaredDistance L2SquaredNorm lcm LinfDistance LinfNorm LinfNormalize log log10 log1p log2 logTrace LpDistance LpNorm LpNormalize max2 min2 minus modulo moduloLegacy moduloOrNull moduloOrZero multiply multiplyDecimal pi plus positiveModulo positiveModuloOrNull pow proportionsZTest radians round roundAge roundBankers roundDown roundDuration roundToExp2 sigmoid sign sin sinh sqrt tan tanh trunc widthBucket",
  nullable: "assumeNotNull coalesce firstNonDefault ifNull isNotNull isNull isNullable isZeroOrNull nullIf",
  random:
    "generateSnowflakeID generateULID generateUUIDv4 generateUUIDv7 rand rand64 randBernoulli randBinomial randCanonical randChiSquared randConstant randExponential randFisherF randLogNormal randNegativeBinomial randNormal randomFixedString randomHadamardTransform randomPrintableASCII randomString randomStringUTF8 randPoisson randStudentT randUniform",
  string:
    "alphaTokens appendTrailingCharIfAbsent ascii caseFoldUTF8 char compareSubstrings concat concatAssumeInjective concatWithSeparator concatWithSeparatorAssumeInjective countEqual countMatches countMatchesCaseInsensitive countSubstrings countSubstringsCaseInsensitive countSubstringsCaseInsensitiveUTF8 damerauLevenshteinDistance editDistance editDistanceUTF8 endsWith endsWithCaseInsensitive endsWithCaseInsensitiveUTF8 endsWithUTF8 extract extractAll extractAllGroupsHorizontal extractAllGroupsVertical extractGroups extractKeyValuePairs extractKeyValuePairsWithEscaping extractTextFromHTML firstLine formatQuery formatQueryOrNull formatQuerySingleLine formatQuerySingleLineOrNull formatReadableDecimalSize formatReadableQuantity formatReadableSize formatReadableTimeDelta formatRow formatRowNoNewline hasPhrase hasSubsequence hasSubsequenceCaseInsensitive hasSubsequenceCaseInsensitiveUTF8 hasSubsequenceUTF8 hasSubstr hasToken hasTokenCaseInsensitive hasTokenCaseInsensitiveOrNull hasTokenOrNull ilike initcap initcapUTF8 jaroSimilarity jaroWinklerSimilarity left leftPad leftPadUTF8 leftUTF8 length lengthUTF8 like locate lower lowerUTF8 match multiFuzzyMatchAllIndices multiFuzzyMatchAny multiFuzzyMatchAnyIndex multiMatchAllIndices multiMatchAny multiMatchAnyIndex multiSearchAllPositions multiSearchAllPositionsCaseInsensitive multiSearchAllPositionsCaseInsensitiveUTF8 multiSearchAllPositionsUTF8 multiSearchAny multiSearchAnyCaseInsensitive multiSearchAnyCaseInsensitiveUTF8 multiSearchAnyUTF8 multiSearchFirstIndex multiSearchFirstIndexCaseInsensitive multiSearchFirstIndexCaseInsensitiveUTF8 multiSearchFirstIndexUTF8 multiSearchFirstPosition multiSearchFirstPositionCaseInsensitive multiSearchFirstPositionCaseInsensitiveUTF8 multiSearchFirstPositionUTF8 ngramDistance ngramDistanceCaseInsensitive ngramDistanceCaseInsensitiveUTF8 ngramDistanceUTF8 ngrams ngramSearch ngramSearchCaseInsensitive ngramSearchCaseInsensitiveUTF8 ngramSearchUTF8 normalizeUTF8NFC normalizeUTF8NFD normalizeUTF8NFKC normalizeUTF8NFKCCasefold normalizeUTF8NFKD overlay overlayUTF8 position positionCaseInsensitive positionCaseInsensitiveUTF8 positionUTF8 printf repeat replaceAll replaceOne replaceRegexpAll replaceRegexpOne reverse reverseBySeparator reverseUTF8 right rightPad rightPadUTF8 rightUTF8 soundex space sparseGrams sparseGramsUTF8 splitByChar splitByNonAlpha splitByRegexp splitByString splitByWhitespace startsWith startsWithCaseInsensitive startsWithCaseInsensitiveUTF8 startsWithUTF8 stem stringBytesEntropy stringBytesUniq stringJaccardIndex stringJaccardIndexUTF8 stringToH3 substring substringIndex substringIndexUTF8 substringUTF8 tokens tokensForLikePattern translate translateUTF8 trimBoth trimLeft trimRight upper upperUTF8 visibleWidth",
  tuple:
    "flattenTuple tuple tupleConcat tupleDivide tupleDivideByNumber tupleElement tupleHammingDistance tupleIntDiv tupleIntDivByNumber tupleIntDivOrZero tupleIntDivOrZeroByNumber tupleMinus tupleModulo tupleModuloByNumber tupleMultiply tupleMultiplyByNumber tupleNames tupleNegate tuplePlus tuplePositiveModuloByNumber tupleToNameValuePairs",
  url: "basename cutFragment cutQueryString cutQueryStringAndFragment cutToFirstSignificantSubdomain cutToFirstSignificantSubdomainCustom cutToFirstSignificantSubdomainCustomRFC cutToFirstSignificantSubdomainCustomWithWWW cutToFirstSignificantSubdomainCustomWithWWWRFC cutToFirstSignificantSubdomainRFC cutToFirstSignificantSubdomainWithWWW cutToFirstSignificantSubdomainWithWWWRFC cutURLParameter cutWWW domain domainRFC domainWithoutWWW domainWithoutWWWRFC extractURLParameter extractURLParameterNames extractURLParameters firstSignificantSubdomain firstSignificantSubdomainCustom firstSignificantSubdomainCustomRFC firstSignificantSubdomainRFC FQDN fragment netloc path pathFull port portRFC protocol topLevelDomain topLevelDomainRFC URLHierarchy URLPathHierarchy",
  window: "cume_dist dense_rank first_value lag lagInFrame last_value lead leadInFrame nth_value ntile percent_rank rank row_number",
  other:
    "addressToLine addressToLineWithInlines addressToSymbol addTupleOfIntervals aiClassify aiEmbed aiExtract aiGenerate aiTranslate authenticatedUser bar bitAnd bitCount bitHammingDistance bitNot bitOr bitPositionsToArray bitRotateLeft bitRotateRight bitShiftLeft bitShiftRight bitSlice bitTest bitTestAll bitTestAny bitXor blockNumber blockSerializedSize blockSize buildId byteHammingDistance byteSize byteSwap caseWithExpression catboostEvaluate colorOKLABToSRGB colorOKLCHToSRGB colorSRGBToOKLAB colorSRGBToOKLCH connectionId conv convertCharset countDigits currentDatabase currentProfiles currentQueryID currentRoles currentSchemas currentUser defaultProfiles defaultRoles demangle dequantizeInt8ToBFloat16 detectCharset detectLanguage detectLanguageMixed detectLanguageUnknown detectTonality displayName dumpColumnStructure enabledProfiles enabledRoles errorCodeToName evalMLMethod filesystemAvailable filesystemCapacity filesystemUnreserved finalizeAggregation financialInternalRateOfReturn financialInternalRateOfReturnExtended financialNetPresentValue financialNetPresentValueExtended fuzzBits generateRandomStructure generateSerialID getClientHTTPHeader getMacro getMaxTableNameLengthForDatabase getMergeTreeSetting getOSKernelVersion getServerPort getServerSetting getSetting getSettingOrDefault getSizeOfEnumType getSubcolumn getTypeSerializationStreams globalNullIn globalNullInIgnoreSet globalVariable hasColumnInTable hasThreadFuzzer highlight highlightQuery hilbertDecode hilbertEncode HMAC hostName icebergBucket icebergTruncate identity ifNotFinite ignore indexHint indexOf indexOfAssumeSorted inIgnoreSet initializeAggregation initialQueryID initialQueryStartTime isConstant isDecimalOverflow isFinite isInfinite isMergeTreePartCoveredBy isNaN isPrime isProbablePrime isValidASCII isValidUTF8 joinGet joinGetOrNull lemmatize lgamma localtime lowCardinalityIndices lowCardinalityKeys mergeTreePartInfo midpoint minSampleSizeContinuous minSampleSizeConversion mortonDecode mortonEncode naiveBayesClassifier naturalSortKey negate neighbor nested normalizeQuery normalizeQueryKeepNames notILike notLike notNullIn notNullInIgnoreSet nullIn nullInIgnoreSet numericIndexedVectorAllValueSum numericIndexedVectorBuild numericIndexedVectorCardinality numericIndexedVectorGetValue numericIndexedVectorPointwiseAdd numericIndexedVectorPointwiseDivide numericIndexedVectorPointwiseEqual numericIndexedVectorPointwiseGreater numericIndexedVectorPointwiseGreaterEqual numericIndexedVectorPointwiseLess numericIndexedVectorPointwiseLessEqual numericIndexedVectorPointwiseMultiply numericIndexedVectorPointwiseNotEqual numericIndexedVectorPointwiseSubtract numericIndexedVectorShortDebugString numericIndexedVectorToMap obfuscateQuery obfuscateQueryWithSeed parseReadableSize parseReadableSizeOrNull parseReadableSizeOrZero partitionId quantizeBFloat16ToInt8 queryID queryString queryStringAndFragment range regexpExtract regexpPosition regexpQuoteMeta regionHierarchy regionIn regionToArea regionToCity regionToContinent regionToCountry regionToDistrict regionToName regionToPopulation regionToTopContinent removeDiacriticsUTF8 replicate revision rowNumberInAllBlocks rowNumberInBlock runningAccumulate runningConcurrency runningDifference runningDifferenceStartingWithFirstValue seriesDecomposeSTL seriesOutliersDetectTukey seriesPeriodDetectFFT serverTimezone serverUUID showCertificate sleep sleepEachRow structureToCapnProtoSchema structureToProtobufSchema subDate subtractTupleOfIntervals svg synonyms tcpPort tgamma throwIf tid tokenizeQuery toValidUTF8 transactionID transactionLatestSnapshot transactionOldestSnapshot transform tryDecrypt tryIdnaEncode tryPunycodeDecode uniqThetaIntersect uniqThetaNot uniqThetaUnion uptime UUIDNumToString UUIDStringToNum UUIDToNum UUIDv7ToDateTime validateNestedArraySizes version windowID wkb wkt zookeeperSessionUptime",
};

const CLICKHOUSE_ALIASES_BY_CANONICAL: Record<string, string[]> = {
  dense_rank: ["denseRank"],
  alphaTokens: ["splitByAlpha"],
  arrayAUCPR: ["arrayPRAUC"],
  arrayFlatten: ["flatten"],
  arrayJoin: ["unnest"],
  arrayRemove: ["array_remove"],
  arrayROCAUC: ["arrayAUC"],
  arrayStringConcat: ["array_to_string"],
  authenticatedUser: ["authUser"],
  base64Decode: ["FROM_BASE64"],
  base64Encode: ["TO_BASE64"],
  byteHammingDistance: ["mismatches"],
  caseWithExpression: ["caseWithExpr"],
  ceil: ["ceiling"],
  concatWithSeparator: ["concat_ws"],
  connectionId: ["connection_id"],
  cosineDistance: ["distanceCosine"],
  cosineDistanceTransposed: ["distanceCosineTransposed"],
  currentDatabase: ["DATABASE", "SCHEMA", "current_database"],
  currentQueryID: ["current_query_id"],
  currentSchemas: ["current_schemas"],
  currentUser: ["current_user", "session_user", "user"],
  dateDiff: ["DATE_DIFF", "TIMESTAMP_DIFF", "timestampDiff"],
  dateTrunc: ["DATE_TRUNC"],
  dotProduct: ["scalarProduct"],
  dotProductTransposed: ["scalarProductTransposed"],
  editDistance: ["levenshteinDistance"],
  editDistanceUTF8: ["levenshteinDistanceUTF8"],
  extractAllGroupsVertical: ["extractAllGroups"],
  extractKeyValuePairs: ["mapFromString", "str_to_map"],
  formatDateTime: ["DATE_FORMAT"],
  formatReadableSize: ["FORMAT_BYTES"],
  FQDN: ["fullHostName"],
  fromDaysSinceYearZero: ["FROM_DAYS"],
  fromUnixTimestamp: ["FROM_UNIXTIME"],
  fromUTCTimestamp: ["from_utc_timestamp"],
  hasAllTokens: ["hasAllToken"],
  hasAnyTokens: ["hasAnyToken"],
  hasPhrase: ["matchPhrase"],
  initialQueryID: ["initial_query_id"],
  initialQueryStartTime: ["initial_query_start_time"],
  IPv4NumToString: ["INET_NTOA"],
  IPv4StringToNum: ["INET_ATON"],
  IPv6NumToString: ["INET6_NTOA"],
  IPv6StringToNum: ["INET6_ATON"],
  isValidASCII: ["isASCII"],
  JSONArrayLength: ["JSON_ARRAY_LENGTH"],
  kostikConsistentHash: ["yandexConsistentHash"],
  L1Distance: ["distanceL1"],
  L1Norm: ["normL1"],
  L1Normalize: ["normalizeL1"],
  L2Distance: ["distanceL2"],
  L2DistanceTransposed: ["distanceL2Transposed"],
  L2Norm: ["normL2"],
  L2Normalize: ["normalizeL2"],
  L2SquaredDistance: ["distanceL2Squared"],
  L2SquaredNorm: ["normL2Squared"],
  leftPad: ["lpad"],
  length: ["CARDINALITY", "OCTET_LENGTH"],
  lengthUTF8: ["CHARACTER_LENGTH", "CHAR_LENGTH"],
  LinfDistance: ["distanceLinf"],
  LinfNorm: ["normLinf"],
  LinfNormalize: ["normalizeLinf"],
  log: ["ln"],
  lower: ["lcase"],
  LpDistance: ["distanceLp"],
  LpNorm: ["normLp"],
  LpNormalize: ["normalizeLp"],
  mapContainsKey: ["mapContains"],
  mapFromArrays: ["MAP_FROM_ARRAYS"],
  match: ["REGEXP_MATCHES"],
  minSampleSizeContinuous: ["minSampleSizeContinous"],
  modulo: ["mod"],
  moduloOrNull: ["modOrNull"],
  multiIf: ["caseWithoutExpr", "caseWithoutExpression"],
  MVTEncodeGeom: ["ST_AsMVTGeom"],
  naturalSortKey: ["NATURAL_SORT_KEY"],
  now: ["current_timestamp", "localtimestamp"],
  parseDateTime: ["TO_UNIXTIME"],
  parseDateTimeOrNull: ["str_to_date"],
  percent_rank: ["percentRank"],
  positionCaseInsensitive: ["instr"],
  positiveModulo: ["pmod", "positive_modulo"],
  positiveModuloOrNull: ["pmodOrNull", "positive_modulo_or_null"],
  pow: ["power"],
  queryID: ["query_id"],
  rand: ["rand32"],
  readWKBLineString: ["ST_LineFromWKB"],
  readWKBMultiLineString: ["ST_MLineFromWKB"],
  readWKBMultiPolygon: ["ST_MPolyFromWKB"],
  readWKBPoint: ["ST_PointFromWKB"],
  readWKBPolygon: ["ST_PolyFromWKB"],
  regexpExtract: ["REGEXP_EXTRACT", "REGEXP_SUBSTR"],
  regexpPosition: ["regexpInstr", "regexp_instr"],
  removeDiacriticsUTF8: ["removeAccentsUTF8"],
  replaceAll: ["replace"],
  replaceRegexpAll: ["REGEXP_REPLACE"],
  rightPad: ["rpad"],
  simpleJSONExtractBool: ["visitParamExtractBool"],
  simpleJSONExtractFloat: ["visitParamExtractFloat"],
  simpleJSONExtractInt: ["visitParamExtractInt"],
  simpleJSONExtractRaw: ["visitParamExtractRaw"],
  simpleJSONExtractString: ["visitParamExtractString"],
  simpleJSONExtractUInt: ["visitParamExtractUInt"],
  simpleJSONHas: ["visitParamHas"],
  sqidEncode: ["sqid"],
  substring: ["byteSlice", "mid", "substr"],
  substringIndex: ["SUBSTRING_INDEX"],
  timeSeriesGroupToTags: ["timeSeriesTagsGroupToTags"],
  timeSeriesIdToGroup: ["timeSeriesIdToTagsGroup"],
  today: ["curdate", "current_date"],
  toDayOfMonth: ["DAY", "DAYOFMONTH"],
  toDayOfWeek: ["DAYOFWEEK"],
  toDayOfYear: ["DAYOFYEAR"],
  toDaysSinceYearZero: ["TO_DAYS"],
  toHour: ["HOUR"],
  toLastDayOfMonth: ["LAST_DAY"],
  toMicrosecond: ["MICROSECOND"],
  toMillisecond: ["MILLISECOND"],
  toMinute: ["MINUTE"],
  toMonth: ["MONTH"],
  toNanosecond: ["NANOSECOND"],
  toQuarter: ["QUARTER"],
  toSecond: ["SECOND"],
  toStartOfFiveMinutes: ["toStartOfFiveMinute"],
  toStartOfInterval: ["date_bin", "time_bucket"],
  toUTCTimestamp: ["to_utc_timestamp"],
  toWeek: ["week"],
  toYear: ["YEAR"],
  toYearWeek: ["yearweek"],
  trimBoth: ["trim"],
  trimLeft: ["ltrim"],
  trimRight: ["rtrim"],
  trunc: ["truncate"],
  tupleMinus: ["vectorDifference"],
  tuplePlus: ["vectorSum"],
  upper: ["ucase"],
  UTCTimestamp: ["UTC_timestamp"],
  widthBucket: ["width_bucket"],
};

const sig = (...parameterGroups: string[][]): ClickHouseFunctionSignature => ({ parameterGroups });

const SIGNATURE_OVERRIDES: Record<string, ClickHouseFunctionSignature[]> = {
  arrayElement: [sig(["array", "index"])],
  arrayFilter: [sig(["lambda", "array", "...arrays"])],
  arrayJoin: [sig(["array"])],
  arrayMap: [sig(["lambda", "array", "...arrays"])],
  cityHash64: [sig(["argument", "...arguments"])],
  concat: [sig(["value", "...values"])],
  cume_dist: [sig([])],
  dense_rank: [sig([])],
  dictGet: [sig(["dictionary", "attribute", "key"])],
  formatDateTime: [sig(["value", "format"]), sig(["value", "format", "time_zone"])],
  geoDistance: [sig(["longitude1", "latitude1", "longitude2", "latitude2"])],
  JSONExtract: [sig(["json", "path", "...paths", "return_type"])],
  JSONExtractString: [sig(["json", "path", "...paths"])],
  lag: [sig(["value"]), sig(["value", "offset"]), sig(["value", "offset", "default"])],
  lagInFrame: [sig(["value"]), sig(["value", "offset"]), sig(["value", "offset", "default"])],
  lead: [sig(["value"]), sig(["value", "offset"]), sig(["value", "offset", "default"])],
  leadInFrame: [sig(["value"]), sig(["value", "offset"]), sig(["value", "offset", "default"])],
  length: [sig(["value"])],
  lower: [sig(["string"])],
  map: [sig(["key", "value", "...pairs"])],
  now: [sig([]), sig(["time_zone"])],
  ntile: [sig(["buckets"])],
  percent_rank: [sig([])],
  rank: [sig([])],
  row_number: [sig([])],
  substring: [sig(["string", "offset"]), sig(["string", "offset", "length"])],
  toDate: [sig(["value"]), sig(["value", "time_zone"])],
  toDateTime: [sig(["value"]), sig(["value", "time_zone"])],
  toStartOfDay: [sig(["value"]), sig(["value", "time_zone"])],
  toStartOfInterval: [sig(["value", "INTERVAL x unit"]), sig(["value", "INTERVAL x unit", "time_zone"]), sig(["value", "INTERVAL x unit", "origin", "time_zone?"])],
  tuple: [sig(["value", "...values"])],
  upper: [sig(["string"])],
  URLHierarchy: [sig(["url"])],
};

const ZERO_ARGUMENT_FUNCTIONS = new Set([
  "buildId",
  "currentDatabase",
  "currentQueryID",
  "currentUser",
  "e",
  "generateUUIDv4",
  "generateUUIDv7",
  "hostName",
  "now",
  "pi",
  "rand",
  "rand64",
  "revision",
  "row_number",
  "serverTimezone",
  "serverUUID",
  "today",
  "timezone",
  "uptime",
  "version",
  "yesterday",
]);

export const CLICKHOUSE_WINDOW_FUNCTION_NAMES = new Set(["cume_dist", "dense_rank", "denseRank", "first_value", "lag", "lagInFrame", "last_value", "lead", "leadInFrame", "nth_value", "ntile", "percent_rank", "percentRank", "rank", "row_number"]);

function definition(name: string, category: ClickHouseFunctionCategory): ClickHouseFunctionDefinition {
  const kind = category === "window" ? "window" : "regular";
  const signatures = Object.prototype.hasOwnProperty.call(SIGNATURE_OVERRIDES, name) ? SIGNATURE_OVERRIDES[name] : [sig(ZERO_ARGUMENT_FUNCTIONS.has(name) ? [] : ["argument", "...arguments?"])];
  const aliases = Object.prototype.hasOwnProperty.call(CLICKHOUSE_ALIASES_BY_CANONICAL, name) ? CLICKHOUSE_ALIASES_BY_CANONICAL[name] : undefined;
  return {
    name,
    kind,
    category,
    signatures,
    aliases,
  };
}

export const CLICKHOUSE_REGULAR_FUNCTIONS: ClickHouseFunctionDefinition[] = Object.entries(CLICKHOUSE_REGULAR_NAMES_BY_CATEGORY).flatMap(([category, names]) =>
  (names ?? "")
    .split(" ")
    .filter(Boolean)
    .map((name) => definition(name, category as ClickHouseFunctionCategory)),
);

export const CLICKHOUSE_FUNCTION_CATEGORY_MANIFEST = [
  { category: "array", minimumCount: 80 },
  { category: "bitmap", minimumCount: 22 },
  { category: "comparison", minimumCount: 46 },
  { category: "conversion", minimumCount: 139 },
  { category: "date-time", minimumCount: 212 },
  { category: "dictionary", minimumCount: 42 },
  { category: "encoding", minimumCount: 35 },
  { category: "geo", minimumCount: 100 },
  { category: "hash", minimumCount: 77 },
  { category: "ip", minimumCount: 19 },
  { category: "json", minimumCount: 48 },
  { category: "map", minimumCount: 23 },
  { category: "math", minimumCount: 89 },
  { category: "nullable", minimumCount: 9 },
  { category: "random", minimumCount: 24 },
  { category: "string", minimumCount: 156 },
  { category: "tuple", minimumCount: 21 },
  { category: "url", minimumCount: 37 },
  { category: "window", minimumCount: 13 },
  { category: "other", minimumCount: 236 },
] as const;
