import type { ClickHouseFunctionDefinition } from "./functionTypes";

/** Static name snapshot from ClickHouse Playground system.table_functions on 2026-07-31. */
export const CLICKHOUSE_TABLE_FUNCTIONS: ClickHouseFunctionDefinition[] = [
  { name: "SQLStandardValues", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "arrowFlight", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "azureBlobStorage", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "azureBlobStorageCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "cluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "clusterAllReplicas", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "cosn", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "deltaLake", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "deltaLakeAzure", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "deltaLakeAzureCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "deltaLakeCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "deltaLakeLocal", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "deltaLakeS3", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "deltaLakeS3Cluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "dictionary", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "executable", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "file", kind: "table", category: "table", signatures: [{ parameterGroups: [["path", "format?", "structure?", "compression?"]] }] },
  { name: "fileCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "filesystem", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "format", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "fuzzJSON", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "fuzzQuery", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "gcs", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "generateRandom", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "generateSeries", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "generate_series", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "hdfs", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "hdfsCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "hive", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "hudi", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "hudiCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "iceberg", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergAzure", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergAzureCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergHDFS", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergHDFSCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergLocal", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergLocalCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergS3", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "icebergS3Cluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "input", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "jdbc", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "loop", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "merge", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "mergeTreeAnalyzeIndexes", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "mergeTreeAnalyzeIndexesUUID", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "mergeTreeIndex", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "mergeTreeProjection", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "mergeTreeTextIndex", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "mongodb", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "mysql", kind: "table", category: "table", signatures: [{ parameterGroups: [["address", "database", "table", "user", "password"]] }] },
  { name: "null", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "numbers", kind: "table", category: "table", signatures: [{ parameterGroups: [["count"]] }, { parameterGroups: [["offset", "count"]] }, { parameterGroups: [["offset", "count", "step"]] }] },
  { name: "numbers_mt", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "odbc", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "oss", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimon", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonAzure", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonAzureCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonHDFS", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonHDFSCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonLocal", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonS3", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "paimonS3Cluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "postgresql", kind: "table", category: "table", signatures: [{ parameterGroups: [["address", "database", "table", "user", "password", "schema?"]] }] },
  { name: "primes", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "prometheusQuery", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "prometheusQueryRange", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "redis", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "remote", kind: "table", category: "table", signatures: [{ parameterGroups: [["addresses", "database", "table", "user?", "password?"]] }] },
  { name: "remoteSecure", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "s3", kind: "table", category: "table", signatures: [{ parameterGroups: [["url", "format?", "structure?", "compression?"]] }] },
  { name: "s3Cluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "sqlite", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "timeSeriesData", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "timeSeriesMetrics", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "timeSeriesSamples", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "timeSeriesSelector", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "timeSeriesTags", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "url", kind: "table", category: "table", signatures: [{ parameterGroups: [["url", "format", "structure?", "headers?"]] }] },
  { name: "urlCluster", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "values", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "view", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "viewExplain", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "viewIfPermitted", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "ytsaurus", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "zeros", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
  { name: "zeros_mt", kind: "table", category: "table", signatures: [{ parameterGroups: [["argument", "...arguments?"]] }] },
];
