services:
  database:
    image: docker.cnb.cool/znb/images/nacos-server:v2.5.2
    container_name: dbx-nacos-2.5
    restart: always
    ports:
      - "${DB_BIND_ADDRESS:-127.0.0.1}:${DB_PORT:-11000}:8848"
      - "${DB_BIND_ADDRESS:-127.0.0.1}:${NACOS_GRPC_PORT:-11001}:9848"
      - "${DB_BIND_ADDRESS:-127.0.0.1}:${NACOS_RAFT_PORT:-11002}:9849"
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      NACOS_AUTH_SYSTEM_TYPE: nacos
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN: "bXlDdXN0b21TZWNyZXRLZXlGb3JOYWNvc1YzMTBNb3JlVGhhbjMyQ2hhcnM="
      NACOS_AUTH_IDENTITY_KEY: dbx_nacos_identity
      NACOS_AUTH_IDENTITY_VALUE: dbx_nacos_identity_value
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 128m
    volumes:
      - data:/home/nacos/data
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8848/nacos/v1/console/health/readiness | grep -q OK"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 20s
volumes:
  data:
