services:
  database:
    image: docker.cnb.cool/znb/images/mariadb:10.11.11
    container_name: dbx-mariadb-10.11
    restart: always
    ports:
      - "${DB_BIND_ADDRESS:-127.0.0.1}:${DB_PORT:-10200}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD:-123456}"
      MARIADB_DATABASE: dbx
    volumes:
      - data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p\"$$MARIADB_ROOT_PASSWORD\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
volumes:
  data:
