services:
  database:
    image: docker.cnb.cool/znb/images/pulsar:4.2.3
    container_name: dbx-pulsar-4.2
    restart: always
    command: ["bin/pulsar", "standalone", "--advertised-address", "localhost"]
    ports:
      - "${DB_BIND_ADDRESS:-127.0.0.1}:${DB_PORT:-11400}:6650"
      - "${DB_BIND_ADDRESS:-127.0.0.1}:${PULSAR_WEB_PORT:-11401}:8080"
    volumes:
      - data:/pulsar/data
      - conf:/pulsar/conf
    healthcheck:
      test: ["CMD-SHELL", "bin/pulsar-admin brokers healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 60
      start_period: 30s
volumes:
  data:
  conf:
